import { APP_ROLES, APP_ROUTE_ROLES, APPLICATION_ROLES } from "../lib/roles.js"

// Presentation rules for the prototype's existing RequireRole guard.
export const APP_PAGE_ACCESS = Object.freeze({
  DASHBOARD: APPLICATION_ROLES,
  COURSES: [APP_ROLES.STUDENT, APP_ROLES.FACULTY],
  SEARCH: [APP_ROLES.STUDENT],
  NOTIFICATIONS: [APP_ROLES.STUDENT],
  MATERIALS: [APP_ROLES.FACULTY],
  ARCHIVE: APP_ROUTE_ROLES.ARCHIVE,
  ADMIN: [APP_ROLES.ADMIN],
  SETTINGS: APPLICATION_ROLES,
})
